### ISSUE TITLE
Problem with smilesdemo

### ISSUE THREAD

**Issue by k0ryphae** [jvermaas/LigninBuilder#2]
When activating writepsfgen.py with Python, inside conda rdkit environment, a following error message is given:

[13:26:28] WARNING: no name column found on line 1
Mol:  0
Traceback (most recent call last):
  File "/home/koryphae/LigninBuilder/smilesdemo/writepsfgen.py", line 243, in <module>
    c1atom = mol.GetAtomWithIdx(match[c1index])
TypeError: tuple indices must be integers or slices, not float

Any help?

**Comment by jvermaas** [comment]
Oooh, I'm betting that this is something related to python 3 making everything floats unless told otherwise. Could you list the steps you took to arrive here? I'm especially keen to know what your python/rdkit versions are.

**Comment by jvermaas** [comment]
Ok, I've just pushed a commit that fixes what was broken when I ran this in python 3.

**Comment by k0ryphae** [comment]
Of course.

So initially I was testing the Lignin-KMC (possibly one of your projects or your group's projects aswell) which generates SMILES code when given parameters. I wanted to try out the SMILES insert to generate something a close to our lignin structure and then further simulate this in GROMACS. So what I precisely did is:

1) installed everything required for Lignin-KMC in the tutorial. 
Conda version 4.9.2
numpy   1.19.2
rdkit - i cant find the version number

**Comment by k0ryphae** [comment]
> Ok, I've just pushed a commit that fixes what was broken when I ran this in python 3.

Thanks. Now for whatever reason I'm getting another error
[16:28:04] WARNING: no name column found on line 1
[16:28:04] WARNING: no name column found on line 2
[16:28:04] WARNING: no name column found on line 3
Mol:  0
/home/koryphae/LigninBuilder/smilesdemo/writepsfgen.py:143: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  for i, monoletter in enumerate(resnamelist[np.argsort(np.array(residuelist, dtype=np.int))][::6]):
Mol:  1
Mol:  2


when in a conda environment I (accessed via conda activate) I type 'conda list' and there rdkit version is 2021.03.1, numpy: 1.20.2

**Comment by k0ryphae** [comment]
> > Ok, I've just pushed a commit that fixes what was broken when I ran this in python 3.
> 
> Thanks. Now for whatever reason I'm getting another error
> [16:28:04] WARNING: no name column found on line 1
> [16:28:04] WARNING: no name column found on line 2
> [16:28:04] WARNING: no name column found on line 3
> Mol: 0
> /home/koryphae/LigninBuilder/smilesdemo/writepsfgen.py:143: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> for i, monoletter in enumerate(resnamelist[np.argsort(np.array(residuelist, dtype=np.int))][::6]):
> Mol: 1
> Mol: 2
> 
> when in a conda environment I (accessed via conda activate) I type 'conda list' and there rdkit version is 2021.03.1, numpy: 1.20.2

And python inside conda environment shows version 3.9.2

**Comment by k0ryphae** [comment]
> Ok, I've just pushed a commit that fixes what was broken when I ran this in python 3.
